# Generated by Django 6.0.6 on 2026-06-27 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Vehicle Name")),
                ("brand", models.CharField(max_length=100, verbose_name="Brand")),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                ("year", models.IntegerField(verbose_name="Year")),
                (
                    "fuel_type",
                    models.CharField(max_length=50, verbose_name="Fuel Type"),
                ),
                (
                    "transmission",
                    models.CharField(max_length=50, verbose_name="Transmission"),
                ),
                (
                    "seating_capacity",
                    models.IntegerField(verbose_name="Seating Capacity"),
                ),
                (
                    "rent_per_day",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Rent Per Day"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cars/",
                        verbose_name="Vehicle Image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Rented", "Rented"),
                            ("Maintenance", "Maintenance"),
                        ],
                        default="Available",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Category Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_date", models.DateField(verbose_name="Pickup Date")),
                ("return_date", models.DateField(verbose_name="Return Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Price"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="rental.car",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="rental.category",
                verbose_name="Category",
            ),
        ),
    ]
