# Generated by Django 6.0.6 on 2026-06-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_car_category_booking_car_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Booked", "Booked"),
                    ("Maintenance", "Maintenance"),
                ],
                default="Available",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
