# Generated by Django 6.0.6 on 2026-06-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0003_alter_car_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_days",
            field=models.IntegerField(default=1, verbose_name="Total Days"),
        ),
    ]
