# Generated by Django 6.0.6 on 2026-06-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0004_booking_total_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="damage_report",
            field=models.TextField(blank=True, null=True, verbose_name="Damage Report"),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Actual Pickup Time"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="return_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Actual Return Time"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("confirmed", "Booked"),
                    ("booked", "Booked"),
                    ("picked_up", "Picked Up"),
                    ("in_use", "In Use"),
                    ("returned", "Returned"),
                    ("completed", "Complete"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
