# Generated by Django 6.0.6 on 2026-06-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0005_booking_damage_report_booking_pickup_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("confirmed", "Booked"),
                    ("booked", "Booked"),
                    ("picked_up", "Picked Up"),
                    ("in_use", "In Use"),
                    ("returned", "Returned"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Booked", "Booked"),
                    ("Maintenance", "Maintenance"),
                    ("Inactive", "Inactive"),
                ],
                default="Available",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
