# Generated by Django 6.0.6 on 2026-06-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0007_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("UPI", "UPI"),
                    ("Credit Card", "Credit Card"),
                    ("Debit Card", "Debit Card"),
                ],
                default="Credit Card",
                max_length=50,
                verbose_name="Payment Method",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Refunded", "Refunded"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
