# Generated by Django 6.0.6 on 2026-06-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0008_alter_payment_payment_method_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_license_verified",
            field=models.BooleanField(default=False, verbose_name="License Verified"),
        ),
    ]
